// @flow

export const modelizeEvent = (apiEvent: ApiEventType): EventType => ({
  title: apiEvent.title,
  description: apiEvent.description,
  author: apiEvent.author,
  startDate: apiEvent.start_date,
  endDate: apiEvent.end_date,
  city: parseInt(apiEvent.city, 10),
  agglo: parseInt(apiEvent.agglo, 10),
  id: apiEvent.id,
  image: apiEvent.image,
  addressLabel: apiEvent.address_label,
  latitude: apiEvent.latitude,
  longitude: apiEvent.longitude,
  distanceToPositionOrCity: 0,
  displayedDistanceToPositionOrCity: '',
  url1: apiEvent.url1,
  url2: apiEvent.url2,
  url3: apiEvent.url3,
  schedule: apiEvent.schedule,
  price: apiEvent.price,
  category: apiEvent.category,
  private: apiEvent.private,
  organizer: apiEvent.organizer,
  organizer_city: apiEvent.organizer_city,
  organizer_logo: apiEvent.organizer_logo,
  organizer_name: apiEvent.organizer_name,
  organizer_type: apiEvent.organizer_type,
  organizer_category_name: apiEvent.organizer_category_name,
  organizer_category_picto: apiEvent.organizer_category_picto,
});
